### ISSUE TITLE
Update Alloy search call to wrap everything in aqs

### ISSUE THREAD

**Issue by struan** [mysociety/open311-adapter#167]
Following a previous announcement from earlier this year, the backwards compatibility AQS models are going to be removed. This change was originally planned to take effect in mid 2020 but more time has been given for all applications to move away from the old models.

(old version goes on 2021-02-25)

### Details

The following endpoints are affected by this change:

    HTTP POST /api/aqs/query
    HTTP POST /api/aqs/join
    HTTP POST /api/aqs/statistics

Currently the request body for these endpoints can be structured in two different ways. The first way is the body being directly the AQS query. The second way is having the AQS query inside the "aqs" property in the body.

Going forwards, only the second model will be supported, since it also allows parameters to be passed to the query. We are therefore moving to remove support for the query directly being passed in the request body and continuing to use this method will result in an Invalid Model error following this change.
Web request that will stop working

HTTP POST /api/aqs/query
{
  "properties": {
   "dodiCode": "designs_myDesign",
   "attributes": ["All"],
 },
 "children": []
}

Web request that is meant to be used

HTTP POST /api/aqs/query
{
 "aqs": {
   "properties": {
     "dodiCode": "designs_myDesign",
     "attributes": ["All"],
   },
   "children": []
 }
}

see [change notification](http://go.announcekit-mail.com/c/eJw1jzFPwzAUhH9NsyVynkPiDh6iqgVUQGpBQFmQ49qthe3nxg4Qfj1mQDrphtN3ujtyMnSMFYYDAVJDTQjLRqu6Ih00AF0Dm7pdd127aIjwHicv1YdJpRPGVhJdceYENIWOQSuvBlC6UZnLtNRaspYum8LF07s5cjXs1WoVnrxY9ug3bHqp8cbcvdwPbHz43vvH3a5Je7oNuk9qvW3d9eFwGy_TzxulzEEoLD-nFOKC9gvYZP3vccqnWAlrcRYhVAb_skss87wgkhmMNWkuHR6VjeWoHH4KW9b9s3zdFiOPaZyEz_fcHFEaleYKx1ORuMbc-FV6TEYbmYvQ_wKgdWOm) for details

**Comment by dracos** [comment]
Was fixed in 60d57a8a89bddf1a85ec021a19dd9102af19fdc7
