### ISSUE TITLE
Alloy get services ignores attributes

### ISSUE THREAD

**Issue by dracos** [mysociety/open311-adapter#194]
Dunno if V2 only. It looks in design->{attributes} but the data is in design->{design}->{attributes}. Other bits of code (e.g. getting the parent attribute) look in the right place. Live code is working fine, so possibly fixing this will break things if it starts to suddenly pull in attributes it wasn't expecting. It's possible this code should be ditched instead or done differently.

**Comment by lizettal** [comment]
@dracos is this for scheduling or is this in relation to the Oxfordshire work?

**Comment by dracos** [comment]
It's not needed for Oxfordshire, I added the required attributes to the code manually rather than having it read them from Alloy, so scheduling at some point (if only to work out whether to remove it or not).

**Comment by lizettal** [comment]
Scheduled for 9 November sprint

**Comment by lizettal** [comment]
Schedule for December

**Comment by dracos** [comment]
Have looked into this:
* Hackney overrides `services` to return a simpler/different services list.
* Oxfordshire doesn't fetch services from open311-adapter at all.
* Northamptonshire therefore is the only one that calls this code at present. It ignores (due to the issue in this ticket) any extra attributes on the source `rfs_design`.

Looking at the attributes set on the designs for each service (unique IDs replaced by "id"):
* Hackney Environment has: defectsDefectNumber (autoincrement in alloy), defectsStatus (default in alloy), tasksStatus (default).
* Hackney Highways has: fMSInspectionRequestFMSID_id (set from fixmystreet_id), fMSInspectionRequestFMSCategory_id (category), fMSInspectionRequestDefectConfirmed_id (set to false in open311 config), inspectionsInspectionNumber (autoincrement), tasksStatus (default), workflowActionPatchLinkAttributeCode (set to "FixMyStreet" in open311 config).
* Northamptonshire has: enquiryInspectionRFS1001181SourceID1009855_id (fixmystreet_id), enquiryInspectionRFS1001181Source1009856_id (defaults to "FixMyStreet"), enquiryInspectionRFS1001181EnquiryType1009857_id (defaults to "Request for Service"), enquiryInspectionRFS1001181Summary1009859_id (title), enquiryInspectionRFS1001181Explanation1009860_id (description), enquiryInspectionRFS1001181ReportedDateTime1009861_id (datetime), enquiryInspectionRFS1001181FMSContact1010927_id (contact), enquiryInspectionRFS1001181Category1011685_id (category), attributes_tasksStatus (defaults to Proposed), inspectionsInspectionNumber (autoincrement). 
* Oxfordshire has: lightingDefectFaultType_id (category), defectsDefectNumber (autoincrement), defectsStatus (defaults to Reported).

So it looks like all attributes are handled by other parts of the code, and "fixing" this code to read required attributes from Alloy and output them as 'extra questions' for FMS would indeed be a bad thing to do. I think we can just remove (or at least formally not use) this code that reads the attributes in, unless there comes a future time where we want to pass attributes through from Alloy to FMS in some automated manner not yet needed.
