### ISSUE TITLE
Confirm photo upload failure shouldn't fail entire request [2hrs]

### ISSUE THREAD

**Issue by davea** [mysociety/open311-adapter#204]
Any failure or error in actions that take place after the successful creation of the enquiry in Confirm (such as storing photo JSON for later upload) must not fail the entire request. If that happens a duplicate enquiry will be created each time FMS retries the Open311 POST Service Request.

**Comment by dracos** [comment]
@davea Is the easiest solution here to move store_enquiry_documents above perform_request? So if the store fails and errors for some reason,the request won't be created. Opposite way round there isn't an issue, if Confirm fails and store_enquiry_documents is run more than once by retries.

**Comment by jacquelinebylau** [comment]
Toggl: https://plan.toggl.com/#timeline/317959/tasks/33843681/embed
