### ISSUE TITLE
Alloy API key changes [15hrs]

### ISSUE THREAD

**Issue by davea** [mysociety/open311-adapter#208]
Yotta are [changing the way API keys are managed in Alloy](https://announcements.alloyapp.io/new-api-key-management-xGuAg).

The important bit for us:

> Important: The way you pass the API key is changing!
>
> The new API keys will need to be passed according to the OAuth 2.0 Bearer token format (RFC 6750). That is a request header named "Authorization" will need to be included, which would look like this:
> 
> `Authorization: Bearer APIKEYVALUEHERE`
>
> This change means that the API keys provided by the old and new mechanisms are not interchangeable and old keys will not be accepted via the Authorization header and new keys will need to be generated.  

Deadline:

> Expected Release Date
> 13th January 2022
>
> Phase 2: Retirement of Existing Token Method
> December 2022

**Comment by lizettal** [comment]
To be scheduled before December 2022

**Comment by dracos** [comment]
`alloy-new-key` branch has the code change in; the key switch sounds like it'll be the annoying thing!

**Comment by lizettal** [comment]
Scheduled for June 2022 https://plan.toggl.com/#timeline/317959/tasks/33070599/embed

**Comment by dracos** [comment]
To get a new API key (here for Oxfordshire live):
```
CUSTOMER_ID=customers_oxfordshireLive_61af3b1c34277ed1048abce8
# Get a user token (doesn't do much)
curl -H"Content-Type: application/json" \
  --data '{"email":"community@mysociety.org","password":"..."}' \
  'https://api.uk.alloyapp.io/api/session'
# Get a customer token from user token
curl -H"Authorization: Bearer <key from step 1>" \
  -H"Content-Type: application/json" \
  --data '' \
  'https://api.uk.alloyapp.io/api/session/customer/$CUSTOMER_ID'
# Get an API key from customer token
curl -H"Authorization: Bearer <key from step 2>" \
  -H"Content-Type: application/json" \
  --data '{"label":"FixMyStreet","enabled":true}' \
  'https://api.uk.alloyapp.io/api/api-key'
```

**Comment by dracos** [comment]
I have new API keys for Oxfordshire Live/Test, Hackney Highways Live/Test, Hackney Estates Live/Test and Hackney  TradeTest.

**Comment by dracos** [comment]
This is live for tilma, will do this next week.
