### ISSUE TITLE
Allow category to be in multiple groups in services response

### ISSUE THREAD

**Issue by struan** [mysociety/open311-adapter#39]
This is to enable categories to appear under multiple groups at the FixMyStreet front end.

Need to
- update confirm code to allow categories under multiple groups in the yaml
- check that the validation allows multiple categories with same name/service
- how to handle service requests for an individual category if it's defined twice in the list.

Part of mysociety/fixmystreet#2475

**Comment by dracos** [comment]
Think was done in e.g. https://github.com/mysociety/open311-adapter/pull/59
